name: My First WorkFlow
on: workflow_dispatch
jobs:
  first-job: 
      runs-on: ubuntu-latest
      steps:
        - name: print hello world
          run: echo "Hello World!"
        - name: print good bye
          run: echo "Good Bye!!"
      
  
